version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: upbit_timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coin
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    command: [
      "postgres",
      "-c", "shared_preload_libraries=timescaledb",
      "-c", "max_connections=200"
    ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:
    driver: local